export interface Recipe {
  id: string;
  title: string;
  category: "savory" | "sweet";
  ingredients: Record<string, string | Record<string, string>>;
  steps: string[];
}


export const recipes: Recipe[] = [
  { 
    id: "1",
    category: "sweet",
    title: "Basque Cheesecake",
    ingredients: {
      "cream cheese": "2 lbs",
      sugar: "1 cup",
      eggs: "3",
      salt: "1/2 tsp",
      "vanilla extract": "1 tsp",
    },
    steps: [
      "Preheat oven to 400°F.",
      "Mix cream cheese, sugar, eggs, salt, and vanilla extract.",
      "Bake for 50 minutes.",
    ],
  },
  {
    id: "2",
    category: "savory",
    title: "Cheese Bread",
    ingredients: {
      "sweet manioc starch": "100g",
      "sour manioc starch": "150g",
      cheese: "200g",
      milk: "50g",
      water: "50g",
      oil: "45g",
      salt: "8g",
      egg: "2",
    },
    steps: [
      "In a pan, mix milk, water, oil, and salt, then bring to a boil.",
      "Add sweet and sour manioc starch to a bowl and pour in the boiled mixture.",
      "Mix well and let cool.",
      "Add the cheese and mix.",
      "Add eggs one at a time until incorporated into the dough.",
      "Form into balls and bake at 180°C for 20 minutes or until golden brown.",
    ],
  },
  {
    id: "3",
    category: "sweet",
    title: "Plain Cake",
    ingredients: {
      eggs: "2",
      sugar: "130g",
      oil: "50g",
      milk: "120g",
      flour: "180g",
      "baking powder": "1 tsp",
    },
    steps: [
      "Preheat oven to 400°F.",
      "Mix eggs and sugar until creamy.",
      "Add oil and milk, then mix well.",
      "Sift flour and baking powder, then mix until smooth.",
      "Bake for 40 minutes or until golden brown.",
    ],
  },
  {
    id: "4",
    category: "savory",
    title: "Cheddar Sauce",
    ingredients: {
      butter: "57g",
      flour: "30g",
      cheddar: "225g",
      milk: "480mL",
      pasta: "225g",
    },
    steps: [
      "Add butter to a pan.",
      "Add flour and whisk until golden.",
      "Add milk and whisk until thickened.",
      "Add cheddar and whisk until melted.",
      "Serve over pasta.",
    ],
  },
  {
    id: "5",
    category: "savory",
    title: "Hummus",
    ingredients: {
      "cooked chickpeas": "250g",
      lemon: "60mL (juice)",
      tahini: "60mL",
      garlic: "1 clove",
      "olive oil": "30mL",
      cumin: "1/2 tsp",
      salt: "to taste",
    },
    steps: [
      "In a food processor, blend tahini, lemon juice, and garlic for 1 minute.",
      "Add chickpeas, cumin, and salt, and process for 1 minute.",
      "Add olive oil and process for 1 minute.",
      "If too thick, gradually add water and process until desired texture.",
    ],
  },
  {
    id: "6",
    category: "savory",
    title: "Potato Gnocchi",
    ingredients: {
      "Asterix potato": "500g",
      parmesan: "100g",
      flour: "100g",
      "salt, black pepper, and nutmeg": "to taste",
    },
    steps: [
      "Add potatoes to cold water, bring to a boil, and cook until soft but firm.",
      "Peel and mash potatoes.",
      "Add parmesan, salt, black pepper, and nutmeg.",
      "Gradually add flour and mix until a homogeneous dough forms.",
      "Roll the dough into logs and cut into 2 cm pieces.",
      "Cook in boiling water until they float to the surface.",
      "Serve with a sauce of your choice.",
    ],
  },
  {
    id: "7",
    category: "savory",
    title: "Queso Sauce",
    ingredients: {
      "processed cheese": "130g",
      water: "40mL",
      milk: "50mL",
      "chopped jalapeño": "1 tbsp",
      "pickled jalapeño": "1/2 tbsp",
      "jalapeño juice": "1/2 tbsp",
      salt: "to taste",
      cumin: "to taste",
    },
    steps: [],
  },
  {
    id: "8",
    category: "savory",
    title: "Pizza Dough",
    ingredients: {
      flour: "3 cups",
      "dry yeast": "10g",
      salt: "1 tsp",
      "warm water": "1 1/4 cups",
      " olive oil": "1/8 cup",
    },
    steps: [
      "In a bowl, mix yeast and sugar with warm water and let it foam (5 minutes).",
      "In a mixer bowl, combine flour and salt, then add yeast mixture and olive oil.",
      "Knead with a dough hook for 15 minutes until smooth.",
      "Place in an oiled bowl, cover, and let rise for 1 hour.",
      "Divide into portions, roll out, and bake as desired.",
    ],
  },
  {
    id: "9",
    category: "sweet",
    title: "Sweet Popcorn",
    ingredients: {
      popcorn: "70g",
      "cocoa powder": "30g",
      sugar: "50g",
      water: "10mL",
      oil: "15g",
    },
    steps: [],
  },
  {
    id: "10",
    category: "sweet",
    title: "American Pancakes",
    ingredients: {
      flour: "195g",
      sugar: "2 tbsp",
      "baking powder": "1 tbsp",
      salt: "1/2 tsp",
      milk: "295mL",
      egg: "1",
      "softened butter": "4 tbsp",
      vanilla: "1 tsp",
    },
    steps: [
      "Combine dry ingredients in a bowl.",
      "Mix wet ingredients in another bowl.",
      "Combine wet and dry mixtures until smooth.",
      "Cook 1/4 cup batter in a greased pan until golden.",
    ],
  },
  {
    id: "11",
    category: "sweet",
    title: "Banana Muffins",
    ingredients: {
      "unsalted butter": "50g",
      sugar: "100g",
      egg: "1",
      "small bananas": "2",
      vanilla: "1/2 tsp",
      flour: "3/4 cup",
      salt: "1/4 tsp",
      "baking soda": "1/2 tsp",
      optional: "Chocolate chips",
    },
    steps: [],
  },
  {
    id: "12",
    category: "sweet",
    title: "Banana Cake",
    ingredients: {
      sugar: "150g",
      water: "60g",
      banana: "3",
      egg: "2",
      oil: "85g",
      milk: "120g",
      flour: "300g",
      "baking powder": "1 tsp",
    },
    steps: [],
  },
  {
    id: "13",
    category: "savory",
    title: "Coxinha",
    ingredients: {
      flour: "160g",
      milk: "250g",
      "mashed potato": "190g",
      butter: "30g",
      salt: "to taste",
      paprika: "to taste",
    },
    steps: [
      "In a pan, bring milk, butter, salt, and paprika to a boil.",
      "Add mashed potato.",
      "Add flour and mix until it forms a dough.",
      "Knead and chill.",
      "Shape and fill as desired.",
    ],
  },
  {
    id: "14",
    category: "savory",
    title: "Hamburger Buns",
    ingredients: {
      tangzhong: {
        milk: "120g",
        flour: "25g",
      },
      dough: {
        sugar: "20g",
        milk: "200g",
        yeast: "7g",
        "milk powder": "30g",
        salt: "7g",
        egg: "1",
        flour: "360g",
        butter: "45g",
      },
    },
    steps: [
      "Cook tangzhong ingredients until thickened.",
      "Combine tangzhong with other ingredients except butter.",
      "Knead for about 11 minutes in a mixer and let rise.",
      "Shape and bake at 180°C.",
    ],
  },
  {
    id: "15",
    category: "sweet",
    title: "NY Cheesecake",
    ingredients: {
      crust: {
        "graham crackers": "100g",
        butter: "40g",
        sugar: "20g",
      },
      filling: {
        "cream cheese": "450g",
        sugar: "163g",
        salt: "1/2 tsp",
        vanilla: "1 tsp",
        eggs: "2",
        "heavy cream": "75g",
        "sour cream": "130g",
        lemon: "1 tbsp",
        cornstarch: "1 tbsp",
      },
    },
    steps: [
      "Crush graham crackers and mix with melted butter and sugar.",
      "Press into a springform pan and bake for 10 minutes at 180°C.",
      "Beat cream cheese until airy and creamy.",
      "Add to cream cheese sugar, salt and vanilla and beat until smooth.",
      "Whisk eggs until smooth.",
      "Add eggs slowly to cream cheese mixture.",
      "Add heavy cream, sour cream and lemon juice, mix until smooth. Add cornstarch, mix again.",
      "Pour the mixture over the crust and tap the pan to remove air bubbles.",
      "Bake for 75 min at 162°C in a hot water bath.",
      "Let it cool on countertop and then refrigerate for at least 4 hours.",
    ],
  },
  {
    id: "16",
    category: "sweet",
    title: "Bolinho de chuva",
    ingredients: {
      flour: "140 g",
      sugar: "80 g",
      milk: "100 mL",
      egg: "1 small",
      "baking powder": "7 g",
      "vanilla extract": "1 tsp",
    },
    steps: [
      "Mix sugar and egg until smooth.",
      "Add milk and vanilla extract to the mixture.",
      "Add flour and baking powder to the mixture.",
      "Fry in oil until golden brown.",
    ],
  },
  {
    id: "17",
    category: "sweet",
    title: "Cookie",
    ingredients: {
      butter: "120 g",
      "brown sugar": "100 g",
      sugar: "100 g",
      egg: "1",
      flour: "225 g",
      salt: "1/2 tsp",
      "vanilla extract": "2 tsp",
      "baking powder": "1/2 tsp",
      "baking soda": "1/2 tsp",
      "chocolate chips": "200 g",
    },
    steps: [
      "Add butter into a pot and heat on medium heat.",
      "Cook until butter is browned.",
      "Cool the butter.",
      "Mix butter and sugars.",
      "Add egg and vanilla extract.",
      "Mix flour, salt, baking powder, and baking soda.",
      "Add chocolate chips.",
      "Leave in the fridge for 30 minutes.",
      "Bake for 20 minutes at 190°C.",
    ],
  },
  {
    id: "18",
    category: "savory",
    title: "Pastel Dough",
    ingredients: {
      flour: "250 g",
      water: "100 mL (hot)",
      oil: "12 g",
      salt: "5 g",
    },
    steps: [
      "Put flour into a mixer.",
      "In another bowl, mix water, salt, and oil.",
      "Wait until the salt is dissolved.",
      "Add the water mixture to the flour.",
      "Mix until the dough has a crumbling texture.",
      "Remove from the mixer and knead until the dough comes together.",
      "Wrap in plastic wrap and let it rest overnight in the fridge.",
      "Roll out the dough and cut it into the desired shape.",
      "Use a filling of choice.",
    ],
  },
  {
    id: "19",
    category: "sweet",
    title: "Carrot Cake",
    ingredients: {
      cake: {
        sugar: "200 g",
        carrots: "100 g",
        oil: "100 g",
        flour: "160 g",
        eggs: "2",
        "baking powder": "1/2 tbsp",
      },
      topping: {
        butter: "2 tablespoons",
        milk: "2 tablespoons",
        "50% cocoa chocolate": "2 tablespoons",
        sugar: "6 tablespoons",
      },
    },
    steps: [
      "Mix sugar, carrots, oil, and eggs in a blender until smooth.",
      "Add mixture to a bowl.",
      "Sift flour and baking powder to mixture.",
      "Bake for 40 minutes at 180°C.",
      "Mix all topping ingredients in a pan.",
      "Cook until thickened.",
      "Pour over the cake.",
    ],
  },
  {
    id: "20",
    category: "savory",
    title: "Focaccia",
    ingredients: {
      flour: "400 g",
      water: "300 g",
      salt: "9 g",
      "olive oil": "15 g",
      yeast: "4 g",
    },
    steps: [
      "Mix flour, water, salt, olive oil and yeast in a bowl.",
      "Knead for 10 minutes.",
      "Let it rest for 30 minutes.",
      "Do 3 sets of stretch and folds every 30 minutes.",
      "Transfer to an oiled container and let it rest overnight in the fridge.",
      "Transfer to an oiled baking sheet and let it rise until doubled.",
      "Add toppings of choice.",
      "Bake at 230°C for 25 minutes or until golden.",
    ],
  },
  {
    id: "21",
    category: "savory",
    title: "Dadinho de tapioca",
    ingredients: {
      milk: "500 g",
      "granulated tapioca starch": "250 g",
      "halloumi cheese": "250 g",
      "salt, black pepper": "to taste",
    },
    steps: [
      "Heat the milk with salt and pepper until it simmers.",
      "Add the tapioca starch and mix well.",
      "Add the cheese and mix until melted.",
      "Pour into a square mold and let it cool.",
      "Cut into small squares and fry until golden brown.",
    ],
  },
  {
    id: "22",
    category: "sweet",
    title: "Basque cheesecake",
    ingredients: {
      "cream cheese": "340 g",
      sugar: "150 g",
      eggs: "3",
      "heavy cream": "60 g",
      salt: "1/4 tsp",
      vanilla: "1/2 tsp",
    },
    steps: [
      "Preheat oven to 200°C.",
      "Mix cream cheese and sugar until smooth.",
      "Whisk eggs and slowly add to the mixture.",
      "Add heavy cream, salt, and vanilla.",
      "Pour into a lined pan and bake for 50 minutes.",
    ],
  },
  {
    id: "23",
    category: "sweet",
    title: "Pudim",
    ingredients: {
      "condensed milk": "2 cans",
      milk: "400 g",
      eggs: "2",
      vanilla: "1 tsp",
    },
    steps: [
      "In a blender add all ingredients and blend until smooth.",
      "Caramelize a pan and pour the mixture.",
      "Bake in a water bath for 90 minutes at 180°C.",
      "Let it cool and refrigerate for at least 6 hours.",
      "Unmold and serve.",
    ],
  },
  {
    id: "24",
    category: "savory",
    title: "Kibe",
    ingredients: {
      "bulgur wheat": "500 g",
      lime: "1",
      onion: "1",
      "olive oil": "1/2 cup",
      mint: "1 cup",
      parsley: "1 cup",
      salt: "to taste",
      "black pepper": "to taste",
    },
    steps: [
      "Soak bulgur wheat in water for 1 hour.",
      "Drain and squeeze out excess water.",
      "In a blender, add bulgur, lime juice, onion, olive oil, mint, parsley, salt, and pepper.",
      "Blend it all together.",
      "Shape into football-shaped kibes, fill with cheese if wanted.",
      "Fry until golden brown.",
    ],
  },
  {
    id: "25",
    category: "sweet",
    title: "Coconut cake",
    ingredients: {
      batter: {
        eggs: "4",
        sugar: "1 cup",
        "vanilla essence": "1 tsp",
        oil: "100 mL",
        flour: "2 cups",
        milk: "1 cup",
        "baking powder": "1 tbsp",
      },
      topping: {
        "coconut milk": "1 cup",
        "condensed milk": "",
        milk: "500 mL",
        "coconut flakes": "1 cup",
      },
    },
    steps: [
      "Mix eggs, sugar, and vanilla essence until it triples in volume.",
      "Add oil and mix well.",
      "Sieve 1 cup of flour, mix. Add half the milk and mix.",
      "Sieve the other cup of flour, mix. Add the rest of the milk and mix.",
      "Add baking powder and mix.",
      "Pour into a greased pan and bake for 45 minutes at 180°C.",
      "Let it cool and cut into squares.",
      "In a bowl, mix coconut milk, condensed milk, and milk.",
      "Soak the cake squares in the mixture.",
      "Top with coconut flakes and wrap in aluminum foil.",
      "Fridge for 8 hours.",
    ],
  },
];
