export const recipes = [
  {
    id: 1,
    type: "sweet",
    title: "Basque Cheesecake",
    ingredients: {
      "cream cheese": "2 lbs",
      sugar: "1 cup",
      eggs: "3",
      salt: "1/2 tsp",
      "vanilla extract": "1 tsp",
    },
    steps: {
      1: "Preheat oven to 400°F.",
      2: "Mix cream cheese, sugar, eggs, salt, and vanilla extract.",
      3: "Bake for 50 minutes.",
    },
  },
  {
    id: 2,
    type: "savory",
    title: "Cheese Bread (Pão de Queijo)",
    ingredients: {
      "sweet tapioca starch": "100g",
      "sour tapioca starch": "150g",
      cheese: "200g",
      milk: "50g",
      water: "50g",
      oil: "45g",
      salt: "8g",
      egg: "2",
    },
    steps: {
      1: "In a pan, mix milk, water, oil, and salt, then bring to a boil.",
      2: "Add sweet and sour tapioca starch to a bowl and pour in the boiled mixture.",
      3: "Mix well and let cool.",
      4: "Add the cheese and mix.",
      5: "Add eggs one at a time until incorporated into the dough.",
      6: "Form into balls and bake at 180°C for 20 minutes or until golden brown.",
    },
  },
  {
    id: 3,
    type: "sweet",
    title: "Plain Cake",
    ingredients: {
      eggs: "2",
      sugar: "130g",
      oil: "50g",
      milk: "120g",
      flour: "180g",
      "baking powder": "1 tsp",
    },
    steps: {
      1: "Preheat oven to 400°F.",
    },
  },
  {
    id: 4,
    type: "savory",
    title: "Cheddar Sauce",
    ingredients: {
      butter: "57g",
      flour: "30g",
      cheddar: "225g",
      milk: "480mL",
      pasta: "225g",
    },
    steps: { 1: "Add butter to a pan." },
  },
  {
    id: 5,
    type: "savory",
    title: "Hummus",
    ingredients: {
      "cooked chickpeas": "250g",
      lemon: "60mL (juice)",
      tahini: "60mL",
      garlic: "1 clove",
      "olive oil": "30mL",
      cumin: "1/2 tsp",
      salt: "to taste",
    },
    steps: {
      1: "In a food processor, blend tahini, lemon juice, and garlic for 1 minute.",
      2: "Add chickpeas, cumin, and salt, and process for 1 minute.",
      3: "Add olive oil and process for 1 minute.",
      4: "If too thick, gradually add water and process until desired texture.",
    },
  },
  {
    id: 6,
    type: "savory",
    title: "Potato Gnocchi",
    ingredients: {
      "Asterix potato": "500g",
      parmesan: "100g",
      flour: "100g",
      "salt, black pepper, and nutmeg": "to taste",
    },
    steps: {
      1: "Add potatoes to cold water, bring to a boil, and cook until soft but firm.",
      2: "Peel and mash potatoes.",
      3: "Add parmesan, salt, black pepper, and nutmeg.",
      4: "Gradually add flour and mix until a homogeneous dough forms.",
      5: "Roll the dough into logs and cut into 2 cm pieces.",
      6: "Cook in boiling water until they float to the surface.",
      7: "Serve with a sauce of your choice.",
    },
  },
  {
    id: 7,
    type: "savory",
    title: "Queso Sauce",
    ingredients: {
      "processed cheese": "130g",
      water: "40mL",
      milk: "50mL",
      "chopped jalapeño": "1 tbsp",
      "pickled jalapeño": "1/2 tbsp",
      "jalapeño juice": "1/2 tbsp",
      salt: "to taste",
      cumin: "to taste",
    },
    steps: { 1: "" },
  },
  {
    id: 8,
    type: "savory",
    title: "Pizza Dough",
    ingredients: {
      flour: "3 cups",
      "dry yeast": "10g",
      salt: "1 tsp",
      "warm water": "1 1/4 cups",
     " olive oil": "1/8 cup",
    },
    steps: {
      1: "In a bowl, mix yeast and sugar with warm water and let it foam (5 minutes).",
      2: "In a mixer bowl, combine flour and salt, then add yeast mixture and olive oil.",
      3: "Knead with a dough hook for 15 minutes until smooth.",
      4: "Place in an oiled bowl, cover, and let rise for 1 hour.",
      5: "Divide into portions, roll out, and bake as desired.",
    },
  },
  {
    id: 9,
    type: "sweet",
    title: "Sweet Popcorn",
    ingredients: {
      popcorn: "70g",
      "cocoa powder": "30g",
      sugar: "50g",
      water: "10mL",
      oil: "15g",
    },
    steps: { 1: "" },
  },
  {
    id: 10,
    type: "sweet",
    title: "American Pancakes",
    ingredients: {
      flour: "195g",
      sugar: "2 tbsp",
      "baking powder": "1 tbsp",
      salt: "1/2 tsp",
      milk: "295mL",
      egg: "1",
      "softened butter": "4 tbsp",
      vanilla: "1 tsp",
    },
    steps: {
      1: "Combine dry ingredients in a bowl.",
      2: "Mix wet ingredients in another bowl.",
      3: "Combine wet and dry mixtures until smooth.",
      4: "Cook 1/4 cup batter in a greased pan until golden.",
    },
  },
  {
    id: 11,
    type: "sweet",
    title: "Banana Muffins",
    ingredients: {
      "unsalted butter": "50g",
      sugar: "100g",
      egg: "1",
      "small bananas": "2",
      vanilla: "1/2 tsp",
      flour: "3/4 cup",
      salt: "1/4 tsp",
      "baking soda": "1/2 tsp",
      optional: "Chocolate chips",
    },
    steps: { 1: "" },
  },
  {
    id: 12,
    type: "sweet",
    title: "Banana Cake",
    ingredients: {
      sugar: "150g",
      water: "60g",
      banana: "3",
      egg: "2",
      oil: "85g",
      milk: "120g",
      flour: "300g",
      "baking powder": "1 tsp",
    },
    steps: { 1: "" },
  },
  {
    id: 13,
    type: "savory",
    title: "Coxinha",
    ingredients: {
      flour: "160g",
      milk: "250g",
      "mashed potato": "190g",
      butter: "30g",
      salt: "to taste",
      paprika: "to taste",
    },
    steps: {
      1: "In a pan, bring milk, butter, salt, and paprika to a boil.",
      2: "Add mashed potato.",
      3: "Add flour and mix until it forms a dough.",
      4: "Knead and chill.",
      5: "Shape and fill as desired.",
    },
  },
  {
    id: 14,
    type: "savory",
    title: "Hamburger Buns",
    ingredients: {
      tangzhong: {
        milk: "120g",
        flour: "25g",
      },
      dough: {
        sugar: "20g",
        milk: "200g",
        yeast: "7g",
        "milk powder": "30g",
        salt: "7g",
        egg: "1",
        flour: "360g",
        butter: "45g",
      },
    },
    steps: {
      1: "Cook tangzhong ingredients until thickened.",
      2: "Combine with other ingredients except butter.",
      3: "Knead and let rise.",
      4: "Shape and bake at 180°C.",
    },
  },
  {
    id: 15,
    type: "sweet",
    title: "NY Cheesecake",
    ingredients: {
      crust: {
        "graham crackers": "100g",
        butter: "40g",
        sugar: "20g",
      },
      filling: {
        "cream cheese": "450g",
        sugar: "100g",
        eggs: "2",
        vanilla: "1 tsp",
      },
    },
    steps: { 1: "" },
  },
  {
    id: 16,
    type: "sweet",
    title: "Bolinho de chuva",
    ingredients: {
      flour: "140 g",
      sugar: "80 g",
      milk: "100 mL",
      egg: "1 small",
      "baking powder": "7 g",
      "vanilla extract": "1 tsp",
    },
    steps: {
      1: "Mix sugar and egg until smooth.",
      2: "Add milk and vanilla extract to the mixture.",
      3: "Add flour and baking powder to the mixture.",
      4: "Fry in oil until golden brown.",
    },
  },
  {
    id: 17,
    type: "sweet",
    title: "Cookie",
    ingredients: {
      butter: "120 g",
      "brown sugar": "100 g",
      sugar: "100 g",
      egg: "1",
      flour: "225 g",
      salt: "1/2 tsp",
      "vanilla extract": "2 tsp",
      "baking powder": "1/2 tsp",
      "baking soda": "1/2 tsp",
      "chocolate chips": "200 g",
    },
    steps: {
      1: "Add butter into a pot and heat on medium heat.",
      2: "Cook until butter is browned.",
      3: "Cool the butter.",
      4: "Mix butter and sugars.",
      5: "Add egg and vanilla extract.",
      6: "Mix flour, salt, baking powder, and baking soda.",
      7: "Add chocolate chips.",
      8: "Leave in the fridge for 30 minutes.",
      9: "Bake for 20 minutes at 190°C.",
    },
  },
  {
    id: 18,
    type: "savory",
    title: "Pastel Dough",
    ingredients: {
      flour: "250 g",
      water: "100 mL (hot)",
      oil: "12 g",
      salt: "5 g",
    },
    steps: {
      1: "Put flour into a mixer.",
      2: "In another bowl, mix water, salt, and oil.",
      3: "Wait until the salt is dissolved.",
      4: "Add the water mixture to the flour.",
      5: "Mix until the dough has a crumbling texture.",
      6: "Remove from the mixer and knead until the dough comes together.",
      7: "Wrap in plastic wrap and let it rest overnight in the fridge.",
      8: "Roll out the dough and cut it into the desired shape.",
      9: "Use a filling of choice.",
    },
  },
  {
    id: 19,
    type: "sweet",
    title: "Carrot Cake",
    ingredients: {
      cake: {
        sugar: "200 g",
        carrots: "100 g",
        oil: "100 g",
        flour: "160 g",
        eggs: "2",
        "baking powder": "1/2 tbsp",
      },
      topping: {
        butter: "2 tablespoons",
        milk: "2 tablespoons",
        "50% cocoa chocolate": "2 tablespoons",
        sugar: "6 tablespoons",
      },
    },
    steps: {},
  },
  {
    id: 20,
    type: "savory",
    title: "Focaccia",
    ingredients: {
      flour: "400 g",
      water: "300 g",
      salt: "9 g",
      "olive oil": "15 g",
      yeast: "4 g",
    },
    steps: {},
  },
  {
    id: 21,
    type: "savory",
    title: "Dadinho de tapioca",
    ingredients: {
      milk: "500 g",
      "granulated tapioca starch": "250 g",
      "halloumi cheese": "250 g",
      "salt, black pepper": "to taste",
    },
    steps: {},
  },
];
