export const recipes = [
  {
    id: 1,
    type: "sweet",
    title: "basque cheesecake",
    ingredients: {
      "cream cheese": "2 lbs",
      sugar: "1 cup",
      eggs: "3",
      salt: "1/2 tsp",
      "vanilla extract": "1 tsp",
    },
    steps: {
      1: "preheat oven 400F",
      2: "mix cream cheese, sugar, eggs, salt, and vanilla extract",
      3: "bake for 50 minutes",
    },
  },
  {
    id: 2,
    type: "savory",
    title: "Pão de queijo",
    ingredients: {
      "polvilho doce": "100g",
      "polvilho azedo": "150g",
      queijo: "200g",
      leite: "50g",
      agua: "50g",
      oleo: "45g",
      sal: "8g",
      ovo: "2",
    },
    steps: {
      1: "Numa panela misturar leite, água, óleo e sal e levar ao fogo até ferver;",
      2: "Colocar o polvilho doce e o polvilho azedo numa tigela e adicionar a mistura fervida;",
      3: "Misturar bem e deixar esfriar;",
      4: "Adicionar o queijo e misturar;",
      5: "Adicionar os ovos um por vez até incorprar na massa;",
      6: "Fazer bolinhas e assar em forno 180C por 20 minutos ou até dourar.",
    },
  },
  {
    id: 3,
    type: "sweet",
    title: "plain cake",
    ingredients: {
      eggs: "2",
      sugar: "130g",
      oil: "50g",
      milk: "120g",
      flour: "180g",
      "baking powder": "1 tsp",
    },
    steps: {
      1: "preheat oven 400F",
    },
  },
  {
    id: 4,
    type: "savory",
    title: "molho de cheddar",
    ingredients: {
      butter: "57 g",
      flour: "30 g farinha",
      cheddar: "225 queijo",
      milk: "480 mL",
      pasta: "225 g",
    },
    steps: { 1: "Colocar manteiga numa panela" },
  },
  {
    id: 5,
    type: "savory",
    title: "Hummus",
    ingredients: {
      "grão de bico cozido": "250 g",
      limão: "60 mL suco de ",
      tahini: "60 mL ",
      alho: "1 dente",
      azeite: "30 mL",
      cominho: "1/2 colher de chá",
      sal: "a gosto",
    },
    steps: {
      1: "Num processador de alimentos adicionar o tahini, suco de limão e alho e processar por 1 minuto;",
      2: "Adicionar o grão de bico, cominho e sal e processar por 1 minuto;",
      3: "Adicionar azeite e processar por 1 minuto;",
      4: "Caso a consistência esteja muito grossa, adicione água aos poucos e processe até atingir a textura desejada.",
    },
  },
  {
    id: 6,
    type: "savory",
    title: "Nhoque de Batata",
    ingredients: {
      "batata asterix": "500 g",
      parmesão: "100 g",
      farinha: "100 g",
      "Sal, pimenta do reina e noz moscada": "a gosto",
    },
    steps: {
      1: "Adicione as batatas em água fria, leva ao fogo e as cozinhe até ficarem macias, porém resistentes;",
      2: "Descasque as batatas e passe-as pelo espremedor;",
      3: "Adicione o parmesão, sal, pimenta do reino e noz moscada;",
      4: "Adicione a farinha aos poucos e misture até formar uma massa homogênea;",
      5: "Faça rolinhos com a massa e corte em pedaços de 2 cm;",
      6: "Cozinhe em água fervente até subirem à superfície;",
      7: "Sirva com o molho de sua preferência.",
    },
  },
  {
    id: 7,
    title: "Molho de queso",
    type: "savory",
    ingredients: {
      "queijo industrializado (polenghi)": "130 g",
      água: "40 mL",
      leite: "50 mL",
      "jalapeño picado": "1 colher sopa",
      "jalapeño conserva": "1/2 colher sopa",
      "suco jalapeño": "1/2 colher sopa",
      sal: "a gosto",
      Cominho: "a gosto",
    },
    steps: { 1: "" },
  },
  {
    id: 8,
    type: "savory",
    title: "Massa de pizza",
    ingredients: {
      farinha: "3 xícaras",
      "fermento biológico": "10 g",
      sal: "1 col chá",
      "água morna": "1 1/4 xícara",
      azeite: "1/8 xícara",
    },
    steps: {
      1: "Numa tigela, misture o fermento e o açúcar. Adicione água morna e misture bem para dissolver. Deixe em temperatura ambiente até espumar – cerca de 5 minutos;",
      2: "Enquanto isso, na tigela da batedeira, misture a farinha com o sal e abra um buraco no centro. Separe uma tigela ou outro recipiente grande e unte com 2 colheres (sopa) de azeite – ela tem que ter espaço suficiente para a massa crescer bastante;",
      3: "Assim que espumar, despeje a mistura de fermento no centro da tigela com farinha. Adicione ¼ de xícara (chá) de azeite e misture, com uma espátula, apenas para incorporar;",
      4: "Para sovar a massa: encaixe a tigela na batedeira com o gancho; comece a bater em velocidade baixa por 5 minutos; aumente a velocidade, aos poucos, para alta e deixe bater por mais 15 minutos até formar uma massa lisa – ela vai descolar da lateral da tigela e formar uma bola no gancho da batedeira;",
      5: "Com as pontas dos dedos (ou uma espátula), desgrude a massa da tigela da batedeira e transfira para o recipiente untado com azeite. Cubra com filme e deixe descansar por 1 hora, até crescer e dobrar de volume;",
      6: "Quando faltar 30 minutos para completar o tempo de crescimento da massa, preaqueça o forno a 250 ºC (temperatura alta). Se for utilizar uma assadeira de pedra sabão, coloque-a dentro do forno ainda frio para aquecer desde o início – caso contrário, ela pode rachar com o choque térmico;",
      7: "Polvilhe uma bancada lisa com farinha de trigo; transfira a massa de pizza para a bancada e, com uma espátula (ou faca) divida em 4 porções. Separe uma porção da massa para abrir e cubra o restante com um pano de prato para não ressecar;",
      8: "Com o rolo de macarrão, abra a massa formando um círculo de cerca de 30 cm de diâmetro – lembre-se de sempre polvilhar a bancada com farinha para a massa não grudar.",
    },
  },
  {
    id: 9,
    type: "sweet",
    title: "Pipoca doce",
    ingredients: {
      pipoca: "70 g",
      nescau: "30 g",
      açucar: "50 g",
      água: "10 mL",
      óleo: "15 g",
    },
    steps: { 1: "" },
  },
  {
    id: 10,
    type: "sweet",
    title: "Panqueca americana",
    ingredients: {
      farinha: "195 g",
      açúcar: "2 col sopa",
      fermento: "1 col sopa",
      sal: "1/2 colher chá",
      leite: "295 mL",
      ovo: "1",
      "manteiga amolecida": "4 col sopa",
      baunilha: "1 col chá",
    },
    steps: {
      1: "Em uma vasilha, adicione a farinha, o açúcar, o fermento e o sal. Misture bem;",
      2: "Em outra vasilha, adicione o leite, o ovo, a manteiga (amolecida - não pode ser 100% derretida) e a baunilha. Misture bem;",
      3: "Adicione a mistura líquida à mistura seca e misture até ficar homogêneo;",
      4: "Aqueça uma frigideira antiaderente em fogo médio e unte com manteiga;",
      5: "Coloque 1/4 de xícara de massa na frigideira e cozinhe até que a parte de baixo esteja dourada e a parte de cima esteja com bolhas;",
      6: "Vire a panqueca e cozinhe até dourar;",
    },
  },
  {
    id: 11,
    type: "sweet",
    title: "Muffin de banana",
    ingredients: {
      "manteiga sem sal": "50 g",
      açúcar: "100 g ",
      ovo: "1",
      "bananas pequenas": "2",
      baunilha: "1/2 col chá",
      farinha: "3/4 cup",
      sal: "1/4 col chá",
      bicarbonato: "1/2 col chá",
      optional: "Chocolate gotas",
    },
    steps: { 1: "" },
  },
  {
    id: 12,
    type: "sweet",
    title: "Bolo de banana",
    ingredients: {
      sugar: "150g",
      agua: "60g",
      banana: "3",
      ovo: "2",
      acucar: "170g",
      oleo: "85g",
      leite: "120g",
      farinha: "300g",
      fermento: "1 colher de chá",
    },
    steps: { 1: "" },
  },
  {
    id: 13,
    type: "savory",
    title: "Coxinha",
    ingredients: {
      farinha: "160g",
      leite: "250g",
      "batata cozida e amassada": "190g",
      manteiga: "30g",
      sal: "a gosto",
      paprica: "a gosto",
    },
    steps: {
      1: "Em uma panela coloque o leite, a manteiga, o sal e a paprica e leve ao fogo até levantar fervura;",
      2: "Adicione a batata cozida e amassada a mistura;",
      3: "Adicione a farinha de uma vez e mexa até desgrudar do fundo da panela e obter uma massa homogenea;",
      4: "Remova a massa da panela e sove até estar bem lisinha;",
      5: "Envolva a massa em plastico filme e deixe descansar na geladeira;",
      6: "Abra a massa e recheie com o recheio de sua preferencia.",
    },
  },

  {
    id: 14,
    type: "savory",
    title: "Pão de hamburguer",
    ingredients: {
      thangzhong: {
        milk: "120g",
        flour: "25g",
      },
      dough: {
        sugar: "20g",
        milk: "200g",
        yeast: "7g",
        "milk powder": "30g",
        salt: "7g",
        egg: "1",
        flour: "360g",
        "unsalted butter": "45g",
        "egg wash": "1 egg whisked with 1 tbsp water",
      },
    },
    steps: {
      1: "Em uma panela coloque o leite e a farinha e leve ao fogo até engrossar;",
      2: "Em um bowl de batedeira, acrescente a mistura de farinha e leite;",
      3: "Adicione o restante dos ingredientes, exceto a manteiga;",
      4: "Ligue a batedeira em velocidade média e bata por 10 minutos;",
      5: "Adicione a manteiga aos poucos e bata até incorporar;",
      6: "Em uma bancada enfarinhada, coloque a massa e dobre para formar uma bola;",
      7: "Coloque a massa em um bowl e cubra com plastico filme ou pano de prato;",
      8: "Deixe descansar até que triplique de volume;",
      9: "Divida a massa em bolinhas de 90g cada;",
      10: "Boleie para que fiquem arrendodas;",
      11: "Coloque as bolinhas em uma forma forrada com papel manteiga;",
      12: "Cubra com pano de prato e deixe descansar por 40 minutos",
      13: "Pincele com ovo batido e leve ao forno pré aquecido a 180C até que dourem;",
      14: "Retire do forno e deixe esfriar.",
    },
  },
  {
    id: 15,
    type: "sweet",
    title: "Cheesecake",
    ingredients: {
      crust: {
        "graham crackers": "100g",
        butter: "40g",
        sugar: "20g",
      },
      filling: {
        "cream cheese": "450g",
        sugar: "163g",
        salt: "1/2 tsp",
        vanilla: "1 tsp",
        eggs: "2",
        "heavy cream": "75g",
        "sour cream": "130g",
        "lemon juice": "1 tbsp",
        cornstarch: "1 tbsp",
      },
    },
    steps: {
      1: "preheat oven to 350F",
      2: "bake for 50 min",
      3: "cool for 1 hour",
      4: "refrigerate for 4 hours",
    },
  },
  {
    id: 16,
    type: "sweet",
    title: "Bolinho de chuva",
    ingredients: {
      flour: "140 g",
      sugar: "80 g",
      milk: "100 mL",
      egg: "1 small",
      "baking powder": "7 g",
      "vanilla extract": "1 tsp",
    },
    steps: { 1: "" },
  },
  {
    id: 17,
    type: "sweet",
    title: "Cookie",
    ingredients: {
      butter: "120 g",
      "brown sugar": "100 g",
      sugar: "100 g",
      egg: "1",
      flour: "225 g",
      salt: "1/2 tsp",
      "vanilla extract": "2 tsp",
      "baking powder": "1/2 tsp",
      "baking soda": "1/2 tsp",
      "chocolate chips": "200 g",
    },
    steps: {
      1: "Add butter into a pot and heat medium heat",
      2: "Cook until butter is browned",
      3: "Cool butter",
      4: "Mix butter and sugar",
      5: "Add egg and vanilla extract",
      6: "Mix flour, salt, baking powder, and baking soda",
      7: "Add chocolate chips",
      8: "Leave in fridge for 30 min",
      9: "Bake for 20 min at 190C",
    },
  },
  {
    id: 18,
    type: "savory",
    title: "Massa de pastel",
    ingredients: {
      flour: "250 g",
      water: "100 mL hot",
      oil: "12 g",
      salt: "5 g",
    },
    steps: {
      1: "Put flour into a mixer",
      2: "In another bowl mix water, salt, and oil",
      3: "Wait until salt is dissolved",
      4: "Add water mixture to flour",
      5: "Mix until dough has a crumbling texture",
      6: "Remove from mixer and knead dough come together",
      7: "Wrap in plastic wrap and let rest (at least) overnight in fridge",
      8: "Roll out dough and cut into wanted shape",
      9: "Use filling of choice",
    },
  },
];
